### ISSUE TITLE
JavaのAPIドキュメントのリンクが違う

### ISSUE THREAD

**Issue by nimiusrd** [ynupc/scalastringcourseday2#1]
[literal.md](https://github.com/ynupc/scalastringcourseday2/blob/master/doc/literal.md)でリンクが間違っているらしいものを7か所確認しましたので修正お願いします。
いずれのリンクも以下のような修正していただければいいと思います。

``` diff
-http://docs.oracle.com/javase/jp/8/api/*
+http://docs.oracle.com/javase/jp/8/docs/api/*
```

**Comment by ynupc** [comment]
どうもありがとうございます。
修正しました。ご確認ください。
